# Generated by Django 6.1 on 2026-09-15 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("recognition", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True)),
                ("awarded_at", models.DateField()),
            ],
            options={
                "ordering": ["-awarded_at"],
            },
        ),
    ]
