# Generated by Django 6.1 on 2026-09-25 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_award_uuid_primary_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="starred_by",
            field=models.ManyToManyField(
                blank=True, related_name="starred_awards", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="starred_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="starred_experiences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
